title:            "@muanchiou"
url:              http://muan.co
permalink:        pretty
highlighter:      pygments
markdown:         kramdown
google_analytics: UA-21332781-7
timezone:         Europe/London
gems:
  - jemoji
  - jekyll-mentions
