title:            Mu-An Chiou - @muanchiou || @muan
url:              http://muan.co
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: UA-21332781-7
timezone:         Europe/London
paginate: 5
gems:
  - jemoji
  - jekyll-mentions
